### ISSUE TITLE
map "var.webapplocs" does not have homogenous types. found TypeString and then TypeList 

### ISSUE THREAD

**Issue by Tommy-Ten** [richeney/terraform-lab4#1]
First of all, thank you for the great labs. At the moment I'm stuck in lab4 and struggling to get it solved. Webapps.tf and variables.tf files are exactly like here but keep getting the following errors:

_Error: azurerm_app_service_plan.free: 3 error(s) occurred:

* azurerm_app_service_plan.free[0]: At column 27, line 1: map "var.webapplocs" does not have homogenous types. found TypeString and then TypeList in:

plan-free-${var.webapplocs[count.index]}
* azurerm_app_service_plan.free[1]: At column 27, line 1: map "var.webapplocs" does not have homogenous types. found TypeString and then TypeList in:

plan-free-${var.webapplocs[count.index]}
* azurerm_app_service_plan.free[2]: At column 27, line 1: map "var.webapplocs" does not have homogenous types. found TypeString and then TypeList in:

plan-free-${var.webapplocs[count.index]}_

Would you be able to point me to the right direction?

**Comment by Tommy-Ten** [comment]
My mistake, this is solved now. 

Variables.tf file had extra "default" line so hence it was failing:

Wrong one: 
variable "webapplocs" {
    default     = {
        description  = "default webapp regions"
        type         = "list"
        default      = []
    }
}

Changed to:
variable "webapplocs" {
        description  = "default webapp regions"
        type         = "list"
        default      = []

**Comment by richeney** [comment]
I'm glad you're finding the labs useful, Tuomas!
